### ISSUE TITLE
Circular dependency detection expects unique class names

### ISSUE THREAD

**Issue by witrin** [artberri/diod#1]
Given classes with the same name leads falsely to `Error: Circular dependency detected: [...]` during build:

**To Reproduce**

```javascript
// module foo/bar
export class A {
}
```

```javascript
// module foo/baz
export class A {
}
```

```javascript
// module foo/index
export * as bar from './bar';
export * as baz from './baz';
```

```javascript
// module qux
import foo from './foo';

export class B {

  constructor( x, y ) {
    // ...
  }
}
```

```javascript
// module bootstrap
import '@abraham/reflection';
import { ContainerBuilder } from 'diod';
import foo from './foo';
import qux from './qux';
// [...]
const builder = new ContainerBuilder();

builder.register(foo.bar.A).useClass(foo.bar.A);
builder.register(foo.baz.A).useClass(foo.baz.A);
builder.use(qux.B).useClass(qux.B).withDependencies([foo.bar.A, foo.baz.A]);

builder.build();
```

**Expected behavior**
Duplicate class names do not lead to false circular dependency errors.

**Comment by artberri** [comment]
@witrin thank you for reporting the bug and the PR fixing it. I've already merged it and published a new DIOD version.

It's very satisfying to see that my work is being used, I hope it is helping to you as much as it is helping to me. Any feedback is welcome :+1:
