### ISSUE TITLE
Register same Service with different injections

### ISSUE THREAD

**Issue by pabloleonalcaide** [artberri/diod#12]
Hi! 

I have been looking for a way to define two implementations for the same service at the same time (For example, `SendMailService`) so that one of them injects the `Logger` implementation `FakeLogger` and another of them the implementation `RealLogger`) with the intention of being able to take one or the other depending on the needs. However, I think we cannot build the container with the same service in duplicate (The error is that the service identified as 'SendMailService' has already been registered and you would need to "unregister it before you can register it again"
The best solution I have found would be the following:
```ts
  // SendMailService.ts
  @Service()
  export class SendMailService {
   public constructor (private readonly logger: Logger) { }
  }

  // Service Register
  diodcontainer.registerFactoryAs(
    c => {
      return new SendMailService(
        env.realImplementation
          ? c.getDependency(RealLogger)
          : c.getDependency(FakeLogger),
      );
    },
    SendMailService,
    DependencyScope.Transient,
  );
  
  // SomeController.ts
  @Controller()
  export class SomeController {
  
    public async doStuffs(): Promise<void> {
      env.realImplementation = true; // or false
      const service = container.get(SendMailService);
      await service.send();
    }
  }
```

Do you think there could be a better solution or that the option of taking advantage of tags that allow a dual implementation to coexist could be introduced in the future?

Example:

```ts
  diodcontainer.registerFactoryAs(
    c => {
      return new SendMailService(c.getDependency(FakeLogger));
    },
    'SendMailServiceFakeLogger',
    DependencyScope.Transient,
  );
```

**Comment by artberri** [comment]
Hi @pabloleonalcaide and sorry for the late response.

In this case, I don't think that you need to register it as a factory, is it not possible to do something like this?

```
diodcontainer.register(Logger).use(env.realImplementation ? RealLogger : FakeLogger)
diodcontainer.registerAndUse(SendMailService)
```

In the example that you are suggesting you do not want to use them as the same time AFAIK, so a tagging system is not necessary in my opinion.

Tagging would be useful if you want to use both in runtime at the same time, but in those cases I think that is better to register the different implementations separately and ask for them explicitly.

I'm going to close the issue because for now tagging is not in the roadmap, but feel free to reopen it if you have another use case that you want to show me, or if the proposed solution does not fit your needs.

A ver si nos vemos algún día, Bilbostack o Salmorejo, quien sabe ;)

Thank you!!!

**Comment by pabloleonalcaide** [comment]
Thanks @artberri !

In my case I think I would need an alternative, since we are not talking about using an "A" implementation for the production environment and an "B" implementation for the test environment, but rather using an "A" implementation for flow 1, where I want the use case to execute some side-effects, and using an "B" implementation for flow 2, where I want the use case not to execute side-effects

Ex: "Register User", if it enters through flow 1, in addition to saving the record in DB, it should send an email to the person, add the user to a list of news, etc.
If it enters through flow 2, it should only save in DB

In any case, I don't want to make noise, I think it's a good idea to keep the issue closed. I hope to see you soon!

**Comment by artberri** [comment]
If that's the case @pabloleonalcaide , I would create two implementations and register them separately: CreateUserService and CreateUserServiceWithEmail, for example. Both can implement the same interface/abstract class if you like. But both should be registered separately.

Then the RegisterUserUseCase should use one or the other based on the business/flow rules you want. But in my opinion, this should be solved with the strategy pattern, an intermediate service provider or something similar, but it is not the responsibility of the dependency injection system.

Obviously this is a completely opinionated statement and I may be wrong, just trying to help.

Regards.

**Comment by pabloleonalcaide** [comment]
Based on opinions, but I think it's more than accurate, it's a solution that could work perfectly without the need to introduce tags or other responsibilities in the dependency injection container.
Thanks once again!
