### ISSUE TITLE
Update broken links from README.md

### ISSUE THREAD

**Issue by anderconal** [artberri/diod#13]
### Broken Link 1

- "create and use your own" link is not working:

![1](https://github.com/artberri/diod/assets/19661411/a347473b-69c1-4e13-a266-505a6b65f0e6)

- The broken link is redirecting to a 404 - page not found:

![2](https://github.com/artberri/diod/assets/19661411/d7f4b8da-5848-43a9-9ecb-83d3547e0e10)

### Broken Link 2

- "TypeScript needs types" link is not working:

![3](https://github.com/artberri/diod/assets/19661411/759af66d-cf0b-4dcc-bca0-19bd3d415250)

- The broken link is resulting in a "We can’t connect to the server at typescriptneedstypes.com." error:

![4](https://github.com/artberri/diod/assets/19661411/4ca86bf8-4acf-4bda-a8aa-27137b9a85c8)

### Link to the PR

https://github.com/artberri/diod/pull/14

**Comment by artberri** [comment]
Thank you very much mate, you are the best 💪 Merged!!!
