### ISSUE TITLE
Register after build?

### ISSUE THREAD

**Issue by joeynq** [artberri/diod#15]
I have a feature to inject a class in container, call it A, and then use is to initiate another class, call it B. The built container doesn't let me inject class B, it has to go through builder.

```ts
// Main.ts
this.#builder.registerAndUser(ClassA);
this.#container = this.#builder.build();
```
```ts
// Child.ts
const instanceA = this.#container.get(ClassA);

// main module doesn't know about class B
const instanceB: ClassB = createFromA(instanceA);

// the feature that I requested.
this.#container.register(ClassB).useInstance(instanceB);
this.#container.rebuild();
```

I wonder if I need to rebuild or we should let user inject directly to Container?

**Comment by artberri** [comment]
Sorry for the late response, but the idea of the containers are to be immutable. You can register the new class with the builder and build it again to create a new container with the new dependency.
